config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'foods#index'
  get '/users', to: 'users#index', as: 'users'
  # get '/recipes', to: 'recipes#index', as: 'recipes'
  # get '/recipes/:id', to: 'recipes#show', as: 'recipes_detail'
  # get '/recipe_foods/new/:id', to: 'recipe_foods#new', as: 'new_recipe_food'
  # post '/recipe_foods', to: 'recipe_foods#create', as: 'create_ing'
  delete '/recipe/remove/:id', to: 'recipes#remove', as: 'food_recipe_remove'
  get '/general_shopping_list/:id', to: 'shopping_lists#index', as: 'general_shopping_list'
  devise_scope :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  # get '/foods', to: 'foods#index'
  # get '/foods/new', to: 'foods#new'

  resources :foods, only: %i[index new create destroy]
  resources :recipes, only: %i[index new create show destroy] do
    resources :recipe_foods, only: %i[new create]
  end
  resources :public_recipes, only: %i[index], as: 'public_recipes'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.role == 'admin'
      can :manage, :all
    else
      can :manage, Recipe, user_id: user.id
      can :manage, Food, user_id: user.id
      can :read, :all
    end
    # Define abilities for the user here. For example:
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user, class_name: 'User', foreign_key: 'user_id'
  has_many :recipe_foods, dependent: :delete_all, foreign_key: 'foods_id'

  validates :measurement_unit, presence: true
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user, class_name: 'User'
  has_many :recipe_foods, dependent: :delete_all, foreign_key: 'recipes_id'
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipes, class_name: 'Recipe'
  belongs_to :foods, class_name: 'Food'
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  validates :name, presence: true

  has_many :foods, foreign_key: 'user_id'
  has_many :recipes, foreign_key: 'user_id'
  has_many :recipe_foods, foreign_key: 'user_id'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :update_allowed_parameters, if: :devise_controller?
  protect_from_forgery with: :exception

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :password, :current_password) }
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def index
    @foods = Food.all
  end

  def new
    # render :new, locals: { user: current_user, food: Food.new }
    @food = Food.new
  end

  def create
    # respond_to do |format|
    # format.html do
    @food = Food.new(food_params)
    @food.user = current_user
    if @food.valid?
      @food.save
      # flash[:notice] = 'New Food Created Successfully'
      redirect_to foods_path
    else
      render :new
    end
    # end
    # end
  end

  def destroy
    @food = Food.find(params[:id])
    @food.destroy
    # flash[:notice] = ['Food Deleted Successfully']
    redirect_to foods_path, notice: 'Successfully removed the Food.'
  end

  private

  def food_params
    params.require(:food).permit!
  end
end

app/controllers/public_recipes_controller.rb
class PublicRecipesController < ApplicationController
  def index
    @public_recipes = Recipe.includes([:user], [:recipe_foods]).where(public: true)
  end
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  before_action :set_recipe_params
  def new
    @recipe_food = RecipeFood.new
    @foods = Food.all
  end

  def create
    @recipe_food = RecipeFood.new(recipe_food_params)
    @me = params.require(:recipe_food).permit(:food_id)
    @food = Food.find_by(id: @me['food_id'])
    @recipe_food.recipes = @recipe
    @recipe_food.foods = @food
    @recipe_food.save!
    # flash[:alert] = 'Ingridents Successfully Added'
    redirect_to recipe_path(@recipe.id)
  end

  private

  def set_recipe_params
    @recipe = Recipe.find(params[:recipe_id])
  end

  def recipe_food_params
    params.require(:recipe_food).permit(:quantity)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = Recipe.all
  end

  def show
    @recipe = Recipe.find(params[:id])
    # @recipe_foods = @recipe.recipe_foods
    @ingridents_list = RecipeFood.includes([:foods]).where(recipes_id: params[:id])
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user = current_user
    if @recipe.valid?
      @recipe.save
      # flash[:notice] = 'New Recipe Created Successfully'
      redirect_to recipes_path
    else
      render :new
    end
  end

  def destroy
    @recipe = Recipe.find(params[:id])
    @recipe.destroy
    redirect_to recipes_path
    # notice: 'Successfully removed the Recipe.'
  end

  def remove
    @ingridents_list = RecipeFood.find(params[:id])
    @ingridents_list.destroy
    redirect_to recipe_path
  end

  private

  def recipe_params
    params.require(:recipe).permit!
  end
end

app/controllers/shopping_lists_controller.rb
class ShoppingListsController < ApplicationController
  def index
    @shopping_lists = RecipeFood.where(recipes_id: params[:id])
    #   puts 'sdasdasdasda'
    #   puts params[:id]
    #  @shopping_lists.each do |shopping_list|
    #     puts shopping_list.foods.name
    #   end
    #   puts 'sdsdsdsds'
    # RecipeFood.includes([:foods]).where(recipes_id: params[:id])
    # @shopping_lists.each do |shopping_list|
    #   shopping_list.food.name
    # end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/public_recipes_helper.rb
module PublicRecipesHelper
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/shopping_lists_helper.rb
module ShoppingListsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/foods/index.html.erb
<h1>List of foods</h1>
    <div>
      <%= button_to "Add food", new_food_path, method: :get %>
    </div>
    <table>
  <thead>
    <tr>
      <th>Food</th>
      <th>Measurement Unit</th>
      <th>Quantity</th>
      <th>Unit Price</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
  <% @foods.each do |food| %>
    <tr>
      <td><%= food.name %></td>
      <td><%= food.measurement_unit %></td>
      <td><%= food.quantity %></td>
      <td>$<%= food.price %></td>
      <td><%= button_to "Delete", food_path(food.id), method: :delete %></td>
    </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/foods/new.html.erb

<%= form_with model: @food, method: :post, local: true, url: foods_path, scope: :food do |f| %> 

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name,  autofocus: true, autocomplete: "name" %>
  </div>

  <div class="field">
    <%= f.label :measurement_unit %><br />
    <%= f.text_field :measurement_unit %>
  </div>

  <div class="field">
    <%= f.label :quantity %><br />
    <%= f.number_field :quantity, autocomplete: "quantity" %>
  </div>

  <div class="field">
    <%= f.label :price %><br />
    <%= f.number_field :price, autocomplete: "new-price" %>
  </div>


  <div class="actions">
    <%= f.submit "Add food to list" %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecipeApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
  <div class="Nav-bar">
  <p class="nav-link"><%= link_to 'Foods', root_path%></p>
  <p class="nav-link"><%= link_to 'Recipes', recipes_path%></p>
  <p class="nav-link"><%= link_to 'Public Recipes', public_recipes_path%></p>
  <% if user_signed_in? %>
  <p class="nav-link"><%= button_to 'Logout', destroy_user_session_path, method: :delete  %></p>
  <%end%>
  </div>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p> 
    <%= yield %>
  </body>
</html>

app/views/public_recipes/index.html.erb
<h1 class="public-recipe-head">Public Recipes</h1>
<% if @public_recipes.length != 0 %>
<% @public_recipes.each do |recipe| %>
  <%recipe.recipe_foods.all.includes([:foods])%>
  <div class="public-recipe-cont">
  <div>
    <div class="public-recipe-mini-count">
      <div>
        <h3>
          <%= link_to recipe.name, recipe_path(id: recipe.id) %>
        </h3>
        <h5>By: <%= recipe.user.name %></h5>
      </div>
      <div>
        <h5>Total foods: <%= recipe.recipe_foods.length %></h5>
        <% sum = 0 %>
        <h5>
          Total price : $ <% recipe.recipe_foods.each do |food| %> <% sum +=
          food.foods.price %> <% end %> <%= sum %>
        </h5>
      </div>
    </div>
   
  </div>
</div>
<%end%>
<% else %>
<div>
<p class="public-recipe-head">No public recipe here</p>
</div>
<%end%>

app/views/recipe_foods/new.html.erb
<%= form_with model: @recipe_food, method: :post, local: true, url: recipe_recipe_foods_path, scope: :recipe_food do |f| %> 
<div class="field">
    <%= f.label :quantity %><br />
    <%= f.number_field :quantity, autocomplete: "quantity" %>
  </div>
  <div class="field">
    <%= f.select :food_id, @foods.map { |food| [food.name, food.id] } , class:'p-2 mb-2' %> 
  </div>
  <div class="actions">
    <%= f.submit "Add Ingredients" %>
  </div>
<%end%>

app/views/recipes/index.html.erb
<div class="add-recipe-button">
<%= button_to 'Add new recipe', new_recipe_path, method: :get%>
</div>
<div class="main-recipe-cont">
<% @recipes.each do |recipe| %>
   <div class="recipe-container">
   <div class="recipe-lists">
   <%= link_to recipe_path(recipe.id) do%>
    <p><%= recipe.name%></p>
   <%end%>
   <p><%= recipe.description%></p>
   </div>
   <%= button_to "Delete", recipe_path(recipe.id), method: :delete%>
  </div>
<%end%>
</div>

app/views/recipes/new.html.erb
<%= form_with model: @recipe, method: :post, local: true, url: recipes_path, scope: :recipe do |f| %> 

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name,  autofocus: true, autocomplete: "name" %>
  </div>

  <div class="field">
    <%= f.label :preparation_time %><br />
    <%= f.number_field :preparation_time %>
  </div>

  <div class="field">
    <%= f.label :cooking_time %><br />
    <%= f.number_field :cooking_time, autocomplete: "quantity" %>
  </div>

  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description, autocomplete: "new-price" %>
  </div>
  <div>
  <%= f.label :public %><br />
  <%= f.select :public, [['Yes', true], ['No', false]] %>
  </div>


  <div class="actions">
    <%= f.submit "Add recipe to list" %>
  </div>
<% end %>

app/views/recipes/show.html.erb
<h1 class="recipe-title"><%= @recipe.name%></h1>
<div class="recipe-detail-controller">
<div>
    <div>
    <p>Preparation Time: <%= @recipe.preparation_time.strftime("%H:%M")%></p>
    </div>
    <div>
    <p>Cooking Time: <%= @recipe.cooking_time.strftime("%H:%M")%></p>
    </div>
</div>
<div>
<% if @recipe.public == true%>
<div class="public-label"><p>Public: </p><div class="public-status-true"><div class="true-ball"></div></div></div>
<%else%>
<div class="public-label"><p>Public: </p><div class="public-status-false"><div class="false-ball"></div></div></div>
<% end %>
</div>
</div>
<div class="recipe-detail-buttons">
<div>
<%= button_to general_shopping_list_path(@recipe.id), method: :get do %>
    <p>Generate Shopping List</p>
<%end%>
</div>
<div>
<%= button_to new_recipe_recipe_food_path(@recipe), method: :get do %>
    <p>Add Ingredients</p>
<%end%>
</div>
</div>


<div class="recipe-detail-table">
<table>
  <thead>
    <tr>
      <th>Food</th>
      <th>Quantity</th>
      <th>Value</th>
      <th>Actions</th>
    </tr>
  </thead>
   <tbody>
   <%@ingridents_list.each do |food| %>
    <tr>
      <td><%= food.foods.name%></td>
      <td><%= food.quantity%><%= food.foods.measurement_unit%></td>
      <td>$<%= food.foods.price%></td>
      <td><%= button_to "Remove", food_recipe_remove_path(food.id), method: :delete%></td>
    </tr>
     <%end%>
  </tbody>
  </table>
  </div>

 

app/views/shopping_lists/index.html.erb
<h2>Shopping List</h2>
 <% sum = 0 %>
<% count = 0 %>
 <% @shopping_lists.each do |shopping_list| %>
<% sum += shopping_list.foods.price %>
      <% count += 1%>
 <%end%>
  <h5>Total value  of food needed: $  <%= sum %></h5>
  <h5> Amount of food:  <%= count %></h5>
      <table>
  <thead>
    <tr>
      <th>Food</th>
      <th>Quantity</th>
      <th>Value</th>
    </tr>
  </thead>
  <tbody>
  <% @shopping_lists.each do |shopping_list| %>
    <tr>
      <td><%= shopping_list.foods.name%></td>
      <td><%= shopping_list.quantity%><%= shopping_list.foods.measurement_unit%></td>
      <td>$<%= shopping_list.foods.price%></td>
    </tr>
    <%end%>
  </tbody>
  </table>
